services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mesaayuda-sql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "BDMayuda*2025"
      MSSQL_PID: "Developer"
    volumes:
      - mssql-data:/var/opt/mssql
      - ./backups:/var/opt/mssql/backups
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'BDMayuda*2025' -Q \"SELECT 1\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped

  db-seed:
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "BDMayuda*2025"
    volumes:
      - ./sql:/sql:ro
    entrypoint: >
      /bin/bash -lc "
      echo 'Ejecutando seed...';
      /opt/mssql-tools/bin/sqlcmd -S db -U SA -P 'BDMayuda*2025' -d master -i /sql/00_create_database.sql;
      for file in /sql/*.sql; do
        if [ \"$file\" != \"/sql/00_create_database.sql\" ]; then
          echo Ejecutando $file;
          /opt/mssql-tools/bin/sqlcmd -S db -U SA -P 'BDMayuda*2025' -d MesaAyudaDB -i \"$file\";
        fi
      done;
      echo 'Seed completo';
      "
    restart: "no"

volumes:
  mssql-data:
